# Generated by Django 5.0.3 on 2024-03-10 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='was_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 20, 39, 30, 277665)),
        ),
    ]
